#' @title Create Excel Report
#' @param dilution_summary The summary table generated by function `summarise_dilution_table`
#' @param file_name Name of the excel file, Default: 'dilution_summary.xlsx'
#' @param sheet_name Sheet name to output the results in Excel, Default: 'DilutionSummary'
#' @export
create_excel_report <- function(dilution_summary,
                                file_name = "dilution_summary.xlsx",
                                sheet_name = "DilutionSummary") {

  ## Excel setup ##

  # Create a new workbook
  my_workbook <- openxlsx::createWorkbook()

  # Create a new worksheet
  openxlsx::addWorksheet(wb = my_workbook, sheetName = sheet_name)

  # Set the width of the columns to fit the column names
  # of the data. Taken from
  # https://stackoverflow.com/questions/45860085/r-autofit-excel-column-width

  font_size <- as.integer(openxlsx::getBaseFont(my_workbook)$size$val)

  openxlsx::setColWidths(wb = my_workbook, sheet = sheet_name,
                         cols = 1:ncol(dilution_summary),
                         widths = nchar(colnames(dilution_summary)) + font_size
                         - 6
                         )

  # Write to worksheet as an Excel Table
  openxlsx::writeDataTable(wb = my_workbook, sheet = sheet_name,
                           x = dilution_summary,
                           withFilter = TRUE,
                           bandedRows = FALSE
                           )

  # Export to file
  openxlsx::saveWorkbook(wb = my_workbook, file = file_name,
                         overwrite = TRUE)

}
