mark_near_zero_columns <- function(dilution_summary) {

  near_zero_columns <- dilution_summary %>%
    dplyr::mutate_if(is.numeric, abs) %>%
    dplyr::summarise_if(is.numeric, min, na.rm = TRUE) %>%
    tidyr::pivot_longer(cols = dplyr::everything(),
                        names_to = "summary_stats",
                        values_to = "min") %>%
    dplyr::filter(.data$min < 0.01) %>%
    dplyr::pull(.data$summary_stats)

  for(variables in near_zero_columns){
    class(dilution_summary[[variables]]) <- "scientific"
  }

  return(dilution_summary)

}


get_column_number_style <- function(dilution_summary,workbook,sheet) {

  classes <- sapply(dilution_summary, class) %>%
    unname()

  #Format numeric style based on column names in dilution_summary
  if(length(which(classes == "numeric")) != 0) {
    s <- openxlsx::createStyle(numFmt = "0.00")
    openxlsx::addStyle(wb = workbook, sheet = sheet, style = s,
                       rows = 2:(nrow(dilution_summary) + 1),
                       cols = which(classes == "numeric"), gridExpand = TRUE)

  }

  if(length(which(classes == "scientific")) != 0) {
    s <- openxlsx::createStyle(numFmt = "0.00E+00")
    openxlsx::addStyle(wb = workbook, sheet = sheet, style = s,
                       rows = 2:(nrow(dilution_summary) + 1),
                       cols = which(classes == "scientific"), gridExpand = TRUE)

  }

}

two_col_cond_format <- function(workbook,sheet,
                                data,conditional_column,
                                threshold_value,
                                pass_criteria = c("above", "below")) {

  col_index <- which(colnames(dilution_summary) %in% conditional_column)

  posStyle <- openxlsx::createStyle(fontColour = "#006100", bgFill = "#C6EFCE")
  negStyle <- openxlsx::createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE")

  if(pass_criteria == "above") {
    posRule <- paste0(">",threshold_value)
    negRule <- paste0("<=",threshold_value)
  } else if(pass_criteria == "below") {
    posRule <- paste0(">=",threshold_value)
    negRule <- paste0("<",threshold_value)
  }

  if(length(col_index) != 0) {
    openxlsx::conditionalFormatting(workbook, sheet, cols = col_index,
                                    rows = 2:(nrow(dilution_summary) + 1),
                                    rule = posRule, style = posStyle, type = "expression")
    openxlsx::conditionalFormatting(workbook, sheet, cols = col_index,
                                    rows = 2:(nrow(dilution_summary) + 1),
                                    rule = negRule, style = negStyle, type = "expression")

  }


}


#' @title Create Excel Report
#' @param dilution_summary The summary table generated by function `summarise_dilution_table`
#' @param file_name Name of the excel file, Default: 'dilution_summary.xlsx'
#' @param sheet_name Sheet name to output the results in Excel, Default: 'Dilution Summary'
#' @export
create_excel_report <- function(dilution_summary,
                                file_name = "dilution_summary.xlsx",
                                sheet_name = "Dilution Summary"
                                ) {

  ## Excel setup ##

  # Create a new workbook
  my_workbook <- openxlsx::createWorkbook()

  # Create a new worksheet
  openxlsx::addWorksheet(wb = my_workbook, sheetName = sheet_name)

  # Create numeric style based on column name
  dilution_summary %>%
    mark_near_zero_columns() %>%
    get_column_number_style(workbook = my_workbook,
                            sheet = sheet_name)

  # Set the width of the columns to fit the column names
  # of the data. Taken from
  # https://stackoverflow.com/questions/45860085/r-autofit-excel-column-width

  font_size <- as.integer(openxlsx::getBaseFont(my_workbook)$size$val)
  openxlsx::setColWidths(wb = my_workbook, sheet = sheet_name,
                         cols = 1:ncol(dilution_summary),
                         widths = nchar(colnames(dilution_summary)) + font_size
                         - 6
                         )

  # Write to worksheet as an Excel Table
  openxlsx::writeDataTable(wb = my_workbook, sheet = sheet_name,
                           x = dilution_summary,
                           withFilter = TRUE,
                           bandedRows = FALSE
                           )

  # Conditional formatting can only be done after data is written to excel sheet
  two_col_cond_format(workbook = my_workbook,sheet = sheet_name,
                      data = dilution_summary,
                      conditional_column = "r_corr",
                      threshold_value = "0.8",
                      pass_criteria = "above"
  )
  two_col_cond_format(workbook = my_workbook,sheet = sheet_name,
                      data = dilution_summary,
                      conditional_column = "pra_linear",
                      threshold_value = "80",
                      pass_criteria = "above"
  )


  # Export to file
  openxlsx::saveWorkbook(wb = my_workbook, file = file_name,
                         overwrite = TRUE)

}
